version: 2
updates:
  - package-ecosystem: gomod
    directory: "api/"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    commit-message:
      prefix: "chore: "
  - package-ecosystem: gomod
    directory: "cli/"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    commit-message:
      prefix: "chore: "
  - package-ecosystem: gomod
    directory: "shared/"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    commit-message:
      prefix: "chore: "
  - package-ecosystem: gomod
    directory: "terraform/provider/"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    commit-message:
      prefix: "chore: "
