linters:
  enable:
    - forbidigo
    - depguard

linters-settings:
  forbidigo:
    forbid:
      - ^fmt\.Errorf(# please use github.com/pkg/errors)?$
      - ^fmt\.Print.*(# please use "github.com/rs/zerolog")$
      - ^spew\.Dump$
  depguard:
    list-type: denylist
    include-go-root: true
    packages-with-error-message:
      # TODO: logrus is in maintenance mode, use a newer alternative
      # - github.com/sirupsen/logrus: "logging is allowed only by zerolog"
      - errors: "please use github.com/pkg/errors instead"
      - golang.org/x/xerrors: "please use github.com/pkg/errors instead"
      - gopkg.in/yaml.v2: "please use gopkg.in/yaml.v3 instead"
    additional-guards:
      # Do not allow test code into "real" code
      - list-type: denylist
        include-go-root: false
        packages:
          - github.com/stretchr/testify
        ignore-file-rules:
          - "**/*_test.go"
          - "**/mock/**/*.go"
