linters:
  enable:
    - deadcode
    - depguard
    - errcheck
    - errorlint
    - forbidigo
    - gci
    - gofmt
    - goimports
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - structcheck
    - typecheck
    - unused
    - varcheck
    - whitespace

linters-settings:
  forbidigo:
    # These are forbidden in non-test files
    # If you have mock functions,etc that are meant to be used in tests
    # please add them here
    forbid:
      - ^fmt\.Errorf(# please use github.com/pkg/errors)?$
      - ^fmt\.Print.*(# please use "github.com/rs/zerolog")$
      - ^spew\.Dump$
      - ^println$
      - ^NewTestHappyConfig$
  depguard:
    list-type: denylist
    include-go-root: true
    packages-with-error-message:
      # TODO: logrus is in maintenance mode, use a newer alternative
      # - github.com/sirupsen/logrus: "logging is allowed only by zerolog"
      - errors: "please use github.com/pkg/errors instead"
      - golang.org/x/xerrors: "please use github.com/pkg/errors instead"
      - gopkg.in/yaml.v2: "please use gopkg.in/yaml.v3 instead"
    additional-guards:
      # Do not allow test code into "real" code
      - list-type: denylist
        include-go-root: false
        packages:
          - github.com/stretchr/testify
        ignore-file-rules:
          - "**/*_test.go"
          - "**/mock/**/*.go"
issues:
  exclude-rules:
    # Exclude some linters from running on tests files.
    - path: _test\.go
      linters:
        - forbidigo
