builds:
  - binary: happy
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - "-w -s -X github.com/chanzuckerberg/happy/pkg/util.GitSha={{.Commit}} -X github.com/chanzuckerberg/happy/pkg/util.Version={{.Version}} -X github.com/chanzuckerberg/happy/pkg/util.Dirty=false -X github.com/chanzuckerberg/happy/pkg/util.Release=true"
    flags:
      - -trimpath

release:
  github:
    owner: chanzuckerberg
    name: happy

brews:
  - description: "A command line tool for happy path."
    tap:
      owner: chanzuckerberg
      name: homebrew-tap
    homepage: "https://github.com/chanzuckerberg/happy"
    test: system "#{bin}/happy"
