variable "tags" {
  description = "Standard tags. Typically generated by fogg."
  type = object({
    env : string,
    owner : string,
    project : string,
    service : string,
    managedBy : string,
  })
}

variable "happy_app_name" {
  type        = string
  description = "The name of the happy application."
}

variable "ecrs" {
  description = "The ECRs that the role should have permissions to"
  type = list({
    repository_arn : string,
  })
  default = []
}

variable "authorized_github_repos" {
  description = "List of Github repos that are authorized to assume the created CI role"
  type        = set(string)
  default     = []
}

variable "eks_cluster_arn" {
  description = "The ARN of the EKS cluster that the role should have permissions to"
  type        = string
  default     = ""
}

variable "dynamodb_table_arn" {
  description = "The ARN of the dynamodb table that the role should have permissions to"
  type        = string
  default     = ""
}