// Code generated by ogen, DO NOT EDIT.

package ogent

// setDefaults set default value of fields.
func (s *AppConfigList) setDefaults() {
	{
		val := AppConfigListSource("environment")
		s.Source = val
	}
}
