// Code generated by ogen, DO NOT EDIT.

package ogent

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// ListAppConfig implements listAppConfig operation.
//
// List AppConfigs.
//
// GET /app-configs
func (UnimplementedHandler) ListAppConfig(ctx context.Context, params ListAppConfigParams) (r ListAppConfigRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ListAppStack implements listAppStack operation.
//
// List AppStacks.
//
// GET /app-stacks
func (UnimplementedHandler) ListAppStack(ctx context.Context, params ListAppStackParams) (r ListAppStackRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ReadAppConfig implements readAppConfig operation.
//
// Finds the AppConfig with the requested ID and returns it.
//
// GET /app-configs/{id}
func (UnimplementedHandler) ReadAppConfig(ctx context.Context, params ReadAppConfigParams) (r ReadAppConfigRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ReadAppStack implements readAppStack operation.
//
// Finds the AppStack with the requested ID and returns it.
//
// GET /app-stacks/{id}
func (UnimplementedHandler) ReadAppStack(ctx context.Context, params ReadAppStackParams) (r ReadAppStackRes, _ error) {
	return r, ht.ErrNotImplemented
}
