// Code generated by ogen, DO NOT EDIT.
package ogent

type DeleteAppConfigRes interface {
	deleteAppConfigRes()
}

type HealthRes interface {
	healthRes()
}

type ListAppConfigRes interface {
	listAppConfigRes()
}

type ReadAppConfigRes interface {
	readAppConfigRes()
}

type SetAppConfigRes interface {
	setAppConfigRes()
}
