// Code generated by ogen, DO NOT EDIT.
package ogent

type HealthRes interface {
	healthRes()
}

type ListAppConfigRes interface {
	listAppConfigRes()
}

type ReadAppConfigRes interface {
	readAppConfigRes()
}
