// Code generated by ent, DO NOT EDIT.

package ogent

import "github.com/chanzuckerberg/happy/api/pkg/ent"

func NewAppConfigList(e *ent.AppConfig) *AppConfigList {
	if e == nil {
		return nil
	}
	var ret AppConfigList
	ret.ID = int64(e.ID)
	ret.CreatedAt = e.CreatedAt
	ret.UpdatedAt = e.UpdatedAt
	ret.DeletedAt = OptDateTime{}
	if e.DeletedAt != nil {
		ret.DeletedAt.SetTo(*e.DeletedAt)
	}
	ret.AppName = e.AppName
	ret.Environment = e.Environment
	ret.Stack = e.Stack
	ret.Key = e.Key
	ret.Value = e.Value
	ret.Source = AppConfigListSource(e.Source)
	return &ret
}

func NewAppConfigLists(es []*ent.AppConfig) []AppConfigList {
	if len(es) == 0 {
		return nil
	}
	r := make([]AppConfigList, len(es))
	for i, e := range es {
		r[i] = NewAppConfigList(e).Elem()
	}
	return r
}

func (ac *AppConfigList) Elem() AppConfigList {
	if ac == nil {
		return AppConfigList{}
	}
	return *ac
}
