linters:
  enable:
    - forbidigo
    - depguard

linters-settings:
  forbidigo:
    # These are forbidden in non-test files
    # If you have mock functions,etc that are meant to be used in tests
    # please add them here
    forbid:
      - ^fmt\.Errorf$
      - ^fmt\.Print.*$
      - ^spew\.Dump$
      - ^println$
      - ^NewTestHappyConfig$
  depguard:
    rules:
      # Main rule: disallow certain core packages across all code
      main:
        list-mode: lax  # can be 'lax', 'original', or 'strict'
        files:
          - $all
        allow:
          - $gostd
        deny:
          - pkg: "errors$"
            desc: please use github.com/pkg/errors instead
          - pkg: "golang.org/x/xerrors"
            desc: please use github.com/pkg/errors instead
          - pkg: "gopkg.in/yaml.v2"
            desc: please use gopkg.in/yaml.v3 instead
          - pkg: "github.com/sirupsen/logrus"
            desc: logging is allowed only by zerolog
      # Secondary rule: prevent test packages from leaking into non-test code
      no-testify-in-prod:
        list-mode: original
        files:
          - "!$test"  # exclude test files
        allow:
          - $gostd
        deny:
          - pkg: "github.com/stretchr/testify"
            desc: test-only package
          - pkg: "github.com/happy/pkg/backend/aws/testbackend"
            desc: test-only package
issues:
  exclude-rules:
    # Exclude some linters from running on tests files.
    - path: _test\.go
      linters:
        - forbidigo
