apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "stack.migrate" . }}
  labels:
  {{- include "stack.labels" . | nindent 4 }}
spec:
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 5
  jobTemplate:
    metadata:
      creationTimestamp: null
    spec:
      backoffLimit: 2
      completions: 1
      manualSelector: false
      parallelism: 1
      template:
        spec:
          automountServiceAccountToken: true
          containers:
          - command:
            - /app/script/happy_migrate.sh
            env:
            - name: APP_HOST
              value: {{ quote .Values.along3Migrate.along3Migrate.env.appHost }}
            - name: APP_NAME
              value: {{ quote .Values.along3Migrate.along3Migrate.env.appName }}
            - name: CONNECTIONS_ENV
              value: {{ quote .Values.along3Migrate.along3Migrate.env.connectionsEnv
                }}
            - name: DEPLOY_ENV_VERSION
              value: {{ quote .Values.along3Migrate.along3Migrate.env.deployEnvVersion
                }}
            - name: GIT_SHA
              value: {{ quote .Values.along3Migrate.along3Migrate.env.gitSha }}
            - name: RACK_ENV
              value: {{ quote .Values.along3Migrate.along3Migrate.env.rackEnv }}
            - name: RAILS_ENV
              value: {{ quote .Values.along3Migrate.along3Migrate.env.railsEnv }}
            - name: RAILS_LOG_TO_STDOUT
              value: {{ quote .Values.along3Migrate.along3Migrate.env.railsLogToStdout
                }}
            - name: RDEV_DEPLOY
              value: {{ quote .Values.along3Migrate.along3Migrate.env.rdevDeploy
                }}
            - name: RELEASE_CREATED_AT
              value: {{ quote .Values.along3Migrate.along3Migrate.env.releaseCreatedAt
                }}
            - name: RUN_IN_HAPPY_PATH
              value: {{ quote .Values.along3Migrate.along3Migrate.env.runInHappyPath
                }}
            - name: SCRUFFY_GIT_SHA
              value: {{ quote .Values.along3Migrate.along3Migrate.env.scruffyGitSha
                }}
            - name: SDL_DATABASE_NAME
              value: {{ quote .Values.along3Migrate.along3Migrate.env.sdlDatabaseName
                }}
            - name: SDL_DATABASE_PORT
              value: {{ quote .Values.along3Migrate.along3Migrate.env.sdlDatabasePort
                }}
            - name: SDL_DATABASE_USER
              value: {{ quote .Values.along3Migrate.along3Migrate.env.sdlDatabaseUser
                }}
            - name: SECRET_KEY_BASE
              value: {{ quote .Values.along3Migrate.along3Migrate.env.secretKeyBase
                }}
            - name: USE_THROW_SENTRY_ERROR
              value: {{ quote .Values.along3Migrate.along3Migrate.env.useThrowSentryError
                }}
            - name: REMOTE_DEV_PREFIX
              value: {{ quote .Values.along3Migrate.along3Migrate.env.remoteDevPrefix
                }}
            - name: DEPLOYMENT_STAGE
              value: {{ quote .Values.along3Migrate.along3Migrate.env.deploymentStage
                }}
            - name: AWS_REGION
              value: {{ quote .Values.along3Migrate.along3Migrate.env.awsRegion }}
            - name: AWS_DEFAULT_REGION
              value: {{ quote .Values.along3Migrate.along3Migrate.env.awsDefaultRegion
                }}
            - name: KUBERNETES_CLUSTER_DOMAIN
              value: {{ quote .Values.kubernetesClusterDomain }}
            envFrom:
            - secretRef:
                name: edu-platform-rdev-along-ssm-secrets
                optional: false
            - secretRef:
                name: postgresql-along3-credentials
                optional: false
            - secretRef:
                name: redis-along3-credentials
                optional: false
            image: {{ .Values.along3Migrate.along3Migrate.image.repository }}:{{
              .Values.along3Migrate.along3Migrate.image.tag | default .Chart.AppVersion
              }}
            imagePullPolicy: {{ .Values.along3Migrate.along3Migrate.imagePullPolicy
              }}
            name: {{ include "stack.migrate" . }}
            resources: {{- toYaml .Values.along3Migrate.along3Migrate.resources |
              nindent 10 }}
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
          dnsPolicy: ClusterFirst
          enableServiceLinks: true
          nodeSelector: {{- toYaml .Values.along3Migrate.nodeSelector | nindent 8 }}
          restartPolicy: Never
          schedulerName: default-scheduler
          securityContext: {}
          serviceAccount: {{ include "stack.migrate" . }}-{{ .Values.deploymentStage }}-{{ include "stack.name" . }}
          serviceAccountName: {{ include "stack.fullname" . }}-{{ include "stack.migrate" . }}-{{ .Values.deploymentStage }}-{{ include "stack.name" . }}
          shareProcessNamespace: false
          terminationGracePeriodSeconds: 30
      ttlSecondsAfterFinished: 10
  schedule: {{ .Values.along3Migrate.schedule | quote }}
  startingDeadlineSeconds: {{ .Values.along3Migrate.startingDeadlineSeconds }}
  successfulJobsHistoryLimit: {{ .Values.along3Migrate.successfulJobsHistoryLimit
    }}
  suspend: {{ .Values.along3Migrate.suspend }}