apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "stack.fullname" . }}-{{ include "service.fullname" . }}
  labels:
    app: {{ include "service.fullname" . }}
    app.kubernetes.io/component: {{ include "service.fullname" . }}
    app.kubernetes.io/part-of: {{ include "stack.name" . }}
  {{- include "stack.labels" . | nindent 4 }}
  annotations:
    alb.ingress.kubernetes.io/actions.redirect: '{"RedirectConfig":{"Port":"443","Protocol":"HTTPS","StatusCode":"HTTP_301"},"Type":"redirect"}'
    alb.ingress.kubernetes.io/backend-protocol: HTTP
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-west-2:254379453707:certificate/9cc3d840-9001-490f-93bf-675516816015
    alb.ingress.kubernetes.io/group.name: stack-along3-electric-dragon
    alb.ingress.kubernetes.io/group.order: "1"
    alb.ingress.kubernetes.io/healthcheck-interval-seconds: "300"
    alb.ingress.kubernetes.io/healthcheck-path: /
    alb.ingress.kubernetes.io/healthcheck-protocol: HTTP
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443},{"HTTP":80}]'
    alb.ingress.kubernetes.io/load-balancer-attributes: idle_timeout.timeout_seconds=60
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/ssl-policy: ELBSecurityPolicy-TLS-1-2-2017-01
    alb.ingress.kubernetes.io/subnets: subnet-0255cf9f09d1661b1,subnet-0ac6ca51ea48a832d,subnet-060ba1b759c5ebeac,subnet-0ed74d012d89a413d
    alb.ingress.kubernetes.io/success-codes: 200-499
    alb.ingress.kubernetes.io/tags: env={{ .Values.deploymentStage }},happy_env={{ .Values.deploymentStage }},happy_last_applied=2023-10-09T03:18:19Z,happy_region=us-west-2,happy_stack_name=along3,managedBy=terraform,owner=infra-eng@chanzuckerberg.com,project=edu-platform,service=happy
    alb.ingress.kubernetes.io/target-group-attributes: deregistration_delay.timeout_seconds=60
    alb.ingress.kubernetes.io/target-type: instance
    alb.ingress.kubernetes.io/wafv2-acl-arn: arn:aws:wafv2:us-west-2:254379453707:regional/webacl/edu-platform-rdev-happy/69ccbde9-6626-44c4-b71d-430aa7b0ee3e
    kubernetes.io/ingress.class: alb
spec:
  rules:
  - http:
      paths:
      - backend:
          service:
            name: redirect
            port:
              name: use-annotation
        path: /*
        pathType: ImplementationSpecific
  - host: along3.edu-platform.rdev.si.czi.technology
    http:
      paths:
      - backend:
          service:
            name: '{{ include "stack.fullname" . }}-{{ include "service.fullname" . }}'
            port:
              number: 4000
        path: /*
        pathType: ImplementationSpecific