apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "service.fullname" . }}-nginx
  labels:
    app: {{ include "service.fullname" . }}
    app.kubernetes.io/component: {{ include "service.fullname" . }}
    app.kubernetes.io/part-of: {{ include "stack.name" . }}
  {{- include "stack.labels" . | nindent 4 }}
  annotations:
    cert-manager.io/cluster-issuer: nginx-issuer
    external-dns.alpha.kubernetes.io/exclude: "true"
    linkerd.io/inject: enabled
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "60"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "60"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "60"
    nginx.ingress.kubernetes.io/service-upstream: "true"
spec:
  ingressClassName: nginx
  rules:
  - host: along3.edu-platform.rdev.si.czi.technology
    http:
      paths:
      - backend:
          service:
            name: {{ include "service.fullname" . }}
            port:
              number: 4000
        path: /
        pathType: ImplementationSpecific
  tls:
  - hosts:
    - along3.edu-platform.rdev.si.czi.technology
    secretName: along3-along-nginx-tls-secret