{{ $global := . }}
{{- range $key, $value := .Values.services }}
{{ $fullServiceName := (printf "%s-%s" $global.stackName $value.name) | trunc 63 | trimSuffix "-" }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "service.fullname" . }}
  labels:
  {{- include "stack.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.along3MigrateRdevAlong3.serviceAccount.annotations | nindent 4 }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "service.fullname" . }}
  labels:
  {{- include "stack.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.along3AlongRdevAlong3.serviceAccount.annotations | nindent 4 }}
{{- end }}