apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: happy-api
  annotations:
    github.com/project-slug: chanzuckerberg/happy
    backstage.io/source-location: url:https://github.com/chanzuckerberg/happy
    happy_app: "true"
  links:
    - url: https://github.com/chanzuckerberg/hapi-infra
      title: View Infra Source
      icon: github
spec:
  type: service
  lifecycle: production
  owner: team-central-infra-eng-core
