apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: hapi
  description: The Happy API that powers the Happy CLI
  annotations:
    github.com/project-slug: chanzuckerberg/happy
    backstage.io/source-location: url:https://github.com/chanzuckerberg/happy
    happy_app: "true"
    happy_directory: api/.happy
  links:
    - url: https://github.com/chanzuckerberg/hapi-infra
      title: View Infra Source
      icon: github
spec:
  type: service
  lifecycle: production
  owner: team-central-infra-eng-core
  system: core-platform
  providesApis:
    - happy-api
