version: "3.8"

services:
  frontend:
    image: "frontend"
    profiles: [ "*" ]
    platform: linux/amd64
    build:
      context: src/api
      dockerfile: Dockerfile
  internal-api:
    image: "internal-api"
    profiles: [ "*" ]
    platform: linux/arm64
    build:
      context: src/internal-api
      dockerfile: Dockerfile

