stackName: along3
deploymentStage: rdev
aws:
  defaultRegion: us-west-2
services:
  - name: "service"
    env:
      additionalEnvVars: {}
      additionalEnvVarsFromConfigMaps:
        items: []
        prefix: ""
      additionalEnvVarsFromSecrets:
        items: []
        prefix: ""
    imageTag: ""
    stackPrefix: ""
    enableServiceMesh: false
    routingMethod: "DOMAIN"
    additionalVolumesFromSecrets:
      items: []
      baseDir: "/var"
    additionalVolumesFromConfigMaps:
      items: []
    createDashboard: false
    skipConfigInjection: false
    cpu: "100m"
    cpuRequests: "10m"
    gpu: null
    gpuRequests: null
    memory: "100Mi"
    memoryRequests: "10Mi"
    cmd: []
    args: []
    imagePullPolicy: "IfNotPresent"
    desiredCount: 2
    maxCount: 2
    scalingCpuThresholdPercentage: 80
    cloudEnv:
      publicSubnets: []
      privateSubnets: []
      databaseSubnets: []
      databaseSubnetGroup: ""
      vpcId: ""
      vpcCidrBlock: ""
    waitForSteadyState: true
    certificateArn: ""
    containerName: "service"
    serviceEndpoints: {}
    healthCheckPath: "/"
    periodSeconds: 3
    initialDelaySeconds: 30
    platformArchitecture: "amd64"
    awsIam:
      serviceAccountName: null
      policyJson: ""
    routing:
      method: "DOMAIN"
      hostMatch: ""
      groupName: ""
      alb: null
      priority: 0
      path: "/*"
      serviceName: ""
      port: 0
      servicePort: 0
      albIdleTimeout: 60
      serviceScheme: "HTTP"
      scheme: "HTTP"
      successCodes: "200-499"
      serviceType: ""
      serviceMesh: false
      allowMeshServices: null
      oidcConfig:
        issuer: ""
        authorizationEndpoint: ""
        tokenEndpoint: ""
        userInfoEndpoint: ""
        secretName: ""
      bypasses: {}
    sidecars: {}
    # sidecars:
    #   sidecar1:
    #     image: "sidecar-image-1"
    #     tag: "1.0.0"
    #     port: 8080
    #     scheme: "HTTP"
    #     memory: "256Mi"
    #     cpu: "250m"
    #     imagePullPolicy: "IfNotPresent"
    #     healthCheckPath: "/health"
    #     initialDelaySeconds: 15
    #     periodSeconds: 5
    tags:
      env: "ADDTAGS"
      owner: "ADDTAGS"
      project: "ADDTAGS"
      service: "ADDTAGS"
      managedBy: "ADDTAGS"
    regionalWafv2Arn: null
    ingressSecurityGroups: []
    additionalNodeSelectors: {}
    additionalPodLabels: {}
    tagMutability: true
    scanOnPush: false