# Auto-generated by 'happy infra'. Do not edit
# Make improvements in happy, so that everyone can benefit.
terraform {
  required_version = ">= 1.3"
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = ">= 5.14"
    }
    kubernetes = {
      source  = "hashicorp/kubernetes"
      version = ">= 2.20"
    }
    datadog = {
      source  = "datadog/datadog"
      version = ">= 3.25.0"
    }
    happy = {
      source  = "chanzuckerberg/happy"
      version = ">= 0.82.1"
    }
  }
}
