apiVersion: batch/v1
kind: CronJob
metadata:
  labels:
    stack: along3
  name: along3-migrate
  namespace: edu-platform-rdev-happy-happy-env
spec:
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 5
  jobTemplate:
    metadata:
      creationTimestamp: null
    spec:
      backoffLimit: 2
      completions: 1
      manualSelector: false
      parallelism: 1
      template:
        spec:
          automountServiceAccountToken: true
          containers:
            - command:
                - /app/script/happy_migrate.sh
              env:
                - name: APP_HOST
                  value: along3.edu-platform.rdev.si.czi.technology
                - name: APP_NAME
                  value: along3
                - name: CONNECTIONS_ENV
                  value: test
                - name: DEPLOY_ENV_VERSION
                  value: get-eks-version-from-hp
                - name: GIT_SHA
                  value: 0cecd7467
                - name: RACK_ENV
                  value: production
                - name: RAILS_ENV
                  value: production
                - name: RAILS_LOG_TO_STDOUT
                  value: enabled
                - name: RDEV_DEPLOY
                  value: 'true'
                - name: RELEASE_CREATED_AT
                  value: '2023-10-08T20:16:36-07:00'
                - name: RUN_IN_HAPPY_PATH
                  value: 'true'
                - name: SCRUFFY_GIT_SHA
                  value: b69e4f13edf1ade0deb0089c28909303de015afe
                - name: SDL_DATABASE_HOST
                  value: >-
                    edu-platform-rdev-happy-sdl.cluster-ciu2wiyqk18f.us-west-2.rds.amazonaws.com
                - name: SDL_DATABASE_NAME
                  value: sdl
                - name: SDL_DATABASE_PASSWORD
                  value: fpnuUHdqiiiB6cZFKUghb2ZEgzEa0t57
                - name: SDL_DATABASE_PORT
                  value: '5432'
                - name: SDL_DATABASE_USER
                  value: sdl
                - name: SECRET_KEY_BASE
                  value: abc123
                - name: USE_THROW_SENTRY_ERROR
                  value: 'true'
                - name: REMOTE_DEV_PREFIX
                  value: /along3
                - name: DEPLOYMENT_STAGE
                  value: rdev
                - name: AWS_REGION
                  value: us-west-2
                - name: AWS_DEFAULT_REGION
                  value: us-west-2
              envFrom:
                - secretRef:
                    name: edu-platform-rdev-along-ssm-secrets
                    optional: false
                - secretRef:
                    name: postgresql-along3-credentials
                    optional: false
                - secretRef:
                    name: redis-along3-credentials
                    optional: false
              image: >-
                254379453707.dkr.ecr.us-west-2.amazonaws.com/along3/rdev/along:sfitzgerald-chanzuckerberg.com-2023-10-09T02-54-43
              imagePullPolicy: IfNotPresent
              name: along3-migrate
              resources:
                limits:
                  cpu: '2'
                  memory: 1Gi
                requests:
                  cpu: 10m
                  memory: 10Mi
              terminationMessagePath: /dev/termination-log
              terminationMessagePolicy: File
          dnsPolicy: ClusterFirst
          enableServiceLinks: true
          nodeSelector:
            kubernetes.io/arch: amd64
          restartPolicy: Never
          schedulerName: default-scheduler
          securityContext: {}
          serviceAccount: along3-migrate-rdev-along3
          serviceAccountName: along3-migrate-rdev-along3
          shareProcessNamespace: false
          terminationGracePeriodSeconds: 30
      ttlSecondsAfterFinished: 10
  schedule: 0 0 1 1 *
  startingDeadlineSeconds: 30
  successfulJobsHistoryLimit: 5
  suspend: true
