{{ $global := . }}

{{- range $key, $value := .Values.services }}
{{ $fullServiceName := (printf "%s-%s" $global.stackName $value.name) | trunc 63 | trimSuffix "-" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $fullServiceName }}
  labels:
  {{- include "service.labels" $fullServiceName | nindent 4 }}
  {{- include "stack.labels" $global | nindent 4 }}
  annotations:
    ad.datadoghq.com/tags: '{"deployment_stage":"{{$global.deploymentStage}}","env":"{{$global.deploymentStage}}","happy_compute":"eks","happy_service":"{{$fullServiceName}}","happy_stack":"{{ include "stack.name" $global }}","managedby":"happy","owner":"{{$global.aws.tags.owner}}","project":"{{$global.aws.tags.project}}","service":"{{$global.aws.tags.service}}"}'
    linkerd.io/inject: {{if eq $value.enableServiceMesh true}}enabled{{else}}disabled{{end}}
spec:
  replicas: {{ $value.scaling.desiredCount }}
  selector:
    matchLabels:
      app: {{$fullServiceName}}
  template:
    metadata:
      labels:
        {{- include "service.labels" $fullServiceName | nindent 8 }}
        {{- include "stack.labels" $global | nindent 8 }}
      annotations:
        ad.datadoghq.com/tags: '{"deployment_stage":"{{$global.deploymentStage}}","env":"{{$global.deploymentStage}}","happy_compute":"eks","happy_service":"{{$fullServiceName}}","happy_stack":"{{ include "stack.name" $global }}","managedby":"happy","owner":"{{$global.aws.tags.owner}}","project":"{{$global.aws.tags.project}}","service":"{{$global.aws.tags.service}}"}'
        {{-if eq $value.enableServiceMesh true -}}
        config.linkerd.io/default-inbound-policy: all-authenticated
        config.linkerd.io/skip-outbound-ports: 25,587,3306,4444,4567,4568,5432,6379,9300,11211
        linkerd.io/inject: enabled
        {{- else}}{{end}}
    spec:
      automountServiceAccountToken: true
      containers:
      - env:
        {{- range $k, $v := $value.env.additionalEnvVars -}}
        - name: {{ $k }}
          value: {{ $v }}
        {{- end }}
      - envFrom:
        #TODO prefix secretRef
        {{- range $k, $v := $value.env.additionalEnvVarsFromConfigMaps.items -}}
        - prefix: {{ $value.env.additionalEnvVarsFromConfigMaps.prefix }}
          value: {{ $v }}
        {{- end }}
        {{- range $k, $v := $value.env.additionalEnvVarsFromSecrets.items -}}
        - prefix: {{ $value.env.additionalEnvVarsFromConfigMaps.prefix }}
          value: {{ $v }}
        {{- end }}
        image: {{ $value.image.repository }}:{{ $value.image.tag }}
        imagePullPolicy: {{ $value.image.pullPolicy }}
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: {{ $value.healthCheck.path | quote}} 
            port: {{ $value.routing.port | quote }}
            scheme: {{ $value.routing.scheme | quote }}
          initialDelaySeconds: {{ $value.healthCheck.initialDelaySeconds | quote }}
          periodSeconds: {{ $value.healthCheck.periodSeconds | quote }}
          successThreshold: 1
          timeoutSeconds: 1
        name: {{ $value.name | quote }}
        ports:
        - containerPort: {{ $value.routing.port | quote }}
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: {{ $value.routing.port | quote }}
            scheme: HTTP
          initialDelaySeconds: {{ $value.healthCheck.initialDelaySeconds | quote }}
          periodSeconds: {{ $value.healthCheck.periodSeconds | quote }}
          successThreshold: 1
          timeoutSeconds: 1
        resources: {{- toYaml $value.resources | nindent 10 }}
        volumeMounts:
        - mountPath: /var/happy
          mountPropagation: None
          name: integration-secret
          readOnly: true
        {{ range $k, $v := $value.volumes.additionalVolumesFromSecrets.items }}
        - mountPath: {{ $value.volumes.additionalVolumesFromSecrets.baseDir }}/{{ $v }}
          name: {{ $v }}
          readOnly: true
        {{ end }}
        {{ range $k, $v := $value.volumes.additionalVolumesFromConfigMaps.items }}
        - mountPath: {{ $value.volumes.additionalVolumesFromSecrets.baseDir }}/{{ $v }}
          name: {{ $v }}
          readOnly: true
        {{ end }} 
      nodeSelector: {{- toYaml (merge $value.additionalNodeSelectors (dict "kubernetes.io/arch" $value.image.platformArchitecture)) }}
      restartPolicy: Always
      serviceAccountName: {{ required "A valid .Values.awsIam.serviceAccountName entry required!" $value.awsIam.serviceAccountName }}
      volumes:
      {{ range $k, $v := $value.volumes.additionalVolumesFromSecrets.items }}
      - name: {{ $v }}
        secret: 
          secretName: {{ $v }}
      {{- end }}
      {{ range $k, $v := $value.volumes.additionalVolumesFromConfigMaps.items }}
      - name: {{ $v }}
        configMap: 
          name: {{ $v }}
      {{- end }} 
      - name: integration-secret
        secret:
          defaultMode: 420
          optional: false
          secretName: integration-secret
{{- end }}