apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "stack.fullname" . }}-{{ include "service.fullname" . }}
  labels:
    app: {{ include "service.fullname" . }}
    app.kubernetes.io/component: {{ include "service.fullname" . }}
    app.kubernetes.io/part-of: {{ include "stack.name" . }}
  {{- include "stack.labels" . | nindent 4 }}
spec:
  maxReplicas: 2
  metrics:
  - resource:
      name: cpu
      target:
        averageUtilization: 80
        type: Utilization
    type: Resource
  minReplicas: 2
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "service.fullname" . }}