{{ $global := . }}
{{- range $key, $value := .Values.services }}
{{- $fullServiceName := printf "%s-%s" $global.Values.stackName $value.name | trunc 63 | trimSuffix "-" }}

{{ if or (eq $value.routing.serviceType "EXTERNAL") (eq $value.routing.serviceType "INTERNAL") }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullServiceName }}
  labels:
    {{- include "service.labels" $fullServiceName | nindent 4 }}
    {{- include "stack.labels" $global | nindent 4 }}
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/healthcheck-interval-seconds: "300"
    alb.ingress.kubernetes.io/healthcheck-path: {{ $value.healthCheck.path | quote }}
    alb.ingress.kubernetes.io/healthcheck-protocol: {{if eq $value.enableServiceMesh true}}HTTPS{{else}}{{ $value.routing.scheme }}{{end}}
    alb.ingress.kubernetes.io/backend-protocol: {{if eq $value.enableServiceMesh true}}HTTPS{{else}}{{ $value.routing.scheme }}{{end}}
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443},{"HTTP":80}]'
    alb.ingress.kubernetes.io/actions.redirect: '{"RedirectConfig":{"Port":"443","Protocol":"HTTPS","StatusCode":"HTTP_301"},"Type":"redirect"}'
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/subnets: {{ required ".Values.aws.cloudEnv.publicSubnets is required" (join "," $global.Values.aws.cloudEnv.publicSubnets) | quote }}
    alb.ingress.kubernetes.io/success-codes: {{ $value.routing.successCodes | quote }}
    alb.ingress.kubernetes.io/tags: env={{$global.deploymentStage}},happy_env={{$global.deploymentStage}},happy_last_applied={{ now | date "20060102150405" }},happy_region={{ $global.Values.aws.region }},happy_stack_name={{ include "stack.name" $global }},managedBy=happy,owner={{ $global.Values.aws.tags.owner }},project={{ $global.Values.aws.tags.project }},service={{ $global.Values.aws.tags.service }}
    alb.ingress.kubernetes.io/target-group-attributes: deregistration_delay.timeout_seconds=60
    alb.ingress.kubernetes.io/target-type: instance
    alb.ingress.kubernetes.io/group.name: stack-along3-electric-dragon # TODO
    alb.ingress.kubernetes.io/group.order: "1" # TODO
    alb.ingress.kubernetes.io/certificate-arn: {{ $value.routing.certificateArn }}
    alb.ingress.kubernetes.io/ssl-policy: ELBSecurityPolicy-TLS-1-2-2017-01    
    alb.ingress.kubernetes.io/load-balancer-attributes: {{ join "," $value.routing.loadBalancerAttributes | quote }}
    {{- if ne $global.Values.aws.wafAclArn "" }}
    alb.ingress.kubernetes.io/wafv2-acl-arn: {{ $global.Values.aws.wafAclArn }}
    {{- end }}
    {{- if eq $value.routing.serviceType "INTERNAL" }}
    alb.ingress.kubernetes.io/auth-type: "oidc"
    alb.ingress.kubernetes.io/auth-on-unauthenticated-request: "authenticate"
    alb.ingress.kubernetes.io/auth-idp-oidc: {{ toJson $value.routing.oidcConfig | quote }}
    {{- end }}
    
spec:
  rules:
  - http:
      paths:
      - backend:
          service:
            name: redirect
            port:
              name: use-annotation
        path: /*
        pathType: ImplementationSpecific
  - host: along3.edu-platform.rdev.si.czi.technology
    http:
      paths:
      - backend:
          service:
            name: {{ $fullServiceName }}
            port:
              number: 4000
        path: /*
        pathType: ImplementationSpecific
{{- end }}
{{- end }}