{{ $global := . }}
{{- range $key, $value := .Values.services }}
{{- $fullServiceName := printf "%s-%s" $global.Values.stackName $value.name | trunc 63 | trimSuffix "-" }}
{{- $service := dict "Values" $global.Values "service" $value -}}
{{ if or (eq $value.routing.serviceType "EXTERNAL") (eq $value.routing.serviceType "INTERNAL") }}

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullServiceName }}-options-bypass
  labels:
    {{- include "service.labels" $fullServiceName | nindent 4 }}
    {{- include "stack.labels" $global | nindent 4 }}
  annotations:
    {{- include "ingress.base.annotations" $service | nindent 4 }}
    alb.ingress.kubernetes.io/group.order: "1" # TODO
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443}]' 
    alb.ingress.kubernetes.io/conditions.{{ $fullServiceName }}: '[{"field":"http-request-method","httpRequestMethodConfig":{"Values":["OPTIONS"]}},{"field":"path-pattern","pathPatternConfig":{"Values":["/*"]}}]' # TODO
spec:
  rules:
  - host: along3.edu-platform.rdev.si.czi.technology
    http:
      paths:
      - backend:
          service:
            name: {{ $fullServiceName }}
            port:
              number: {{if eq $global.Values.serviceMesh.enabled true}}443{{else}}{{$value.routing.servicePort | int}}{{end}}
        pathType: ImplementationSpecific
{{- end }}
{{- end }}