apiVersion: policy.linkerd.io/v1alpha1
kind: MeshTLSAuthentication
metadata:
  name: {{ include "service.fullname" . }}
  labels:
    app: {{ include "service.fullname" . }}
    app.kubernetes.io/component: {{ include "service.fullname" . }}
    app.kubernetes.io/part-of: {{ include "stack.name" . }}
  {{- include "stack.labels" . | nindent 4 }}
spec:
  identityRefs:
  - kind: ServiceAccount
    name: edu-ps-belong-edu-ps-belong-rdev-edu-ps-belong
    namespace: edu-platform-rdev-happy-happy-env
  - kind: ServiceAccount
    name: edu-ps-tofu-edu-ps-tofu-rdev-edu-ps-tofu
    namespace: edu-platform-rdev-happy-happy-env
  - kind: ServiceAccount
    name: nginx-ingress-ingress-nginx
    namespace: nginx-encrypted-ingress