{{ $global := . }}

{{- range $key, $value := .Values.services }}
{{ $fullServiceName := (printf "%s-%s" $global.stackName $value.name) | trunc 63 | trimSuffix "-" }}

apiVersion: v1
kind: Secret
metadata:
  name: {{ $fullServiceName }}-oidc-config
  labels:
  {{- include "service.labels" $fullServiceName | nindent 4 }}
  {{- include "stack.labels" $global | nindent 4 }}
data:
  clientID: {{ required "$value.oidcConfig.clientID is required" $value.oidcConfig.clientID
    | b64enc | quote }}
  clientSecret: {{ required "$value.oidcConfig.clientSecret is required" $value.oidcConfig.clientSecret
    | b64enc | quote }}
{{- end }}