{{ $global := . }}
{{- range $key, $value := .Values.services }}
{{ $fullServiceName := (printf "%s-%s" $global.Values.stackName $value.name) | trunc 63 | trimSuffix "-" }}
{{- if eq $value.routing.serviceType "INTERNAL" }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $fullServiceName }}-oidc-config
  {{ if eq .Values.serviceMesh.enabled true }}
  namespace: nginx-encrypted-ingress
  {{- end }}
  labels:
  {{- include "service.labels" $fullServiceName | nindent 4 }}
  {{- include "stack.labels" $global | nindent 4 }}
data:
  clientID: {{ required ".Values.services[].routing.oidcConfig.clientID is required" $value.routing.oidcConfig.clientID
    | b64enc | quote }}
  clientSecret: {{ required ".Values.services[].routing.oidcConfig.clientSecret is required" $value.routing.oidcConfig.clientSecret
    | b64enc | quote }}
{{- end }}
{{- end }}