apiVersion: v1
kind: Secret
metadata:
  name: {{ include "service.fullname" . }}-oidc-config
  labels:
  {{- include "stack.labels" . | nindent 4 }}
data:
  clientID: {{ required "along3OidcConfig.clientID is required" .Values.along3OidcConfig.clientID
    | b64enc | quote }}
  clientSecret: {{ required "along3OidcConfig.clientSecret is required" .Values.along3OidcConfig.clientSecret
    | b64enc | quote }}