apiVersion: v1
automountServiceAccountToken: true
kind: ServiceAccount
metadata:
  annotations:
    eks.amazonaws.com/role-arn: >-
      arn:aws:iam::254379453707:role/edu-platform-rdev-eks/along3-migrate-rdev-along3
  name: along3-migrate-rdev-along3
  namespace: edu-platform-rdev-happy-happy-env
---
apiVersion: v1
automountServiceAccountToken: true
kind: ServiceAccount
metadata:
  annotations:
    eks.amazonaws.com/role-arn: >-
      arn:aws:iam::254379453707:role/edu-platform-rdev-eks/along3-along-rdev-along3
  name: along3-along-rdev-along3
  namespace: edu-platform-rdev-happy-happy-env
