apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "stack.fullname" . }}-along3-migrate-rdev-along3
  labels:
  {{- include "stack.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.along3MigrateRdevAlong3.serviceAccount.annotations | nindent 4 }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "stack.fullname" . }}-along3-along-rdev-along3
  labels:
  {{- include "stack.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.along3AlongRdevAlong3.serviceAccount.annotations | nindent 4 }}