apiVersion: v1
kind: Service
metadata:
  name: {{ include "service.fullname" . }}
  labels:
    app: {{ include "service.fullname" . }}
    app.kubernetes.io/component: {{ include "service.fullname" . }}
  {{- include "stack.labels" . | nindent 4 }}
spec:
  type: {{ .Values.along3Along.type }}
  selector:
    app: {{ include "service.fullname" . }}
  ports:
	{{- .Values.along3Along.ports | toYaml | nindent 2 -}}