apiVersion: v1
kind: Service
metadata:
  annotations:
  labels:
    app: along3-along
    app.kubernetes.io/component: along3-along
    app.kubernetes.io/managed-by: happy
    app.kubernetes.io/name: along3
    app.kubernetes.io/part-of: along3
  name: along3-along
  namespace: edu-platform-rdev-happy-happy-env
spec:
  ports:
    - port: 4000
      protocol: TCP
      targetPort: 4000
  selector:
    app: along3-along
  sessionAffinity: None
  type: NodePort
