{{ $global := . }}
{{- range $key, $value := .Values.services }}
{{ $fullServiceName := (printf "%s-%s" $global.stackName $value.name) | trunc 63 | trimSuffix "-" }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $fullServiceName }}
  labels:
  {{- include "service.labels" $fullServiceName | nindent 4 }}
  {{- include "stack.labels" $global | nindent 4 }}
spec:
  type: {{-if or (eq $value.routing.serviceType "PRIVATE") (eq $value.enableServiceMesh true) -}}ClusterIP{{- else -}}NodePort{{- end }}
  selector:
    app: {{ include "service.fullname" . }}
  ports:
	{{- .Values.along3Along.ports | toYaml | nindent 2 -}}
{{- end }}