apiVersion: v1
kind: Service
metadata:
  name: {{ include "stack.fullname" . }}-along3-along
  labels:
    app: along3-along
    app.kubernetes.io/component: along3-along
    app.kubernetes.io/part-of: along3
  {{- include "stack.labels" . | nindent 4 }}
spec:
  type: {{ .Values.along3Along.type }}
  selector:
    app: along3-along
  {{- include "stack.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.along3Along.ports | toYaml | nindent 2 -}}