config_version: v1
terraform_version: 0.13.5
default_env: rdev
app: test-app
default_compose_env: ".env.ecr"
slice_default_tag: "branch-trunk"
slices:
    frontend:
        build_images:
            - frontend
    backend:
        build_images:
            - backend
    fullstack:
        build_images:
            - frontend
            - backend
environments:
    rdev:
        aws_profile: "test-dev"
        secret_arn: "happy/env-rdev-config"
        terraform_directory: ".happy/terraform/envs/rdev"
        log_group_prefix: "/dp/rdev"
    stage:
        aws_profile: "test-stage"
        secret_arn: "happy/env-stage-config"
        terraform_directory: ".happy/terraform/envs/stage"
        delete_protected: true
        auto_run_migrations: false
        log_group_prefix: "/dp/staging"
    prod:
        aws_profile: "test-prod"
        secret_arn: "happy/env-prod-config"
        terraform_directory: ".happy/terraform/envs/prod"
        delete_protected: true
        auto_run_migrations: false
        log_group_prefix: "/dp/prod"
tasks:
    migrate:
        - "migrate_db_task_definition_arn"
    delete:
        - "delete_db_task_definition_arn"
