apiVersion: policy.linkerd.io/v1alpha1
kind: AuthorizationPolicy
metadata:
  labels:
    app: ntf-stable-notifications-service
    app.kubernetes.io/component: ntf-stable-notifications-service
    app.kubernetes.io/managed-by: happy
    app.kubernetes.io/name: ntf-stable
    app.kubernetes.io/part-of: ntf-stable
  name: ntf-stable-notifications-service-policy
  namespace: edu-platform-rdev-happy-happy-env
spec:
  requiredAuthenticationRefs:
    - group: policy.linkerd.io
      kind: MeshTLSAuthentication
      name: ntf-stable-notifications-service-mesh-tls-auth
  targetRef:
    group: policy.linkerd.io
    kind: Server
    name: ntf-stable-notifications-service-server
