// Package model provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.16.2 DO NOT EDIT.
package model

import (
	"time"
)

// Defines values for AppConfigListSource.
const (
	Environment AppConfigListSource = "environment"
	Stack       AppConfigListSource = "stack"
)

// AppConfigList defines model for AppConfigList.
type AppConfigList struct {
	AppName     string              `json:"app_name"`
	CreatedAt   time.Time           `json:"created_at"`
	DeletedAt   *time.Time          `json:"deleted_at,omitempty"`
	Environment string              `json:"environment"`
	Id          int64               `json:"id"`
	Key         string              `json:"key"`
	Source      AppConfigListSource `json:"source"`
	Stack       string              `json:"stack"`
	UpdatedAt   time.Time           `json:"updated_at"`
	Value       string              `json:"value"`
}

// AppConfigListSource defines model for AppConfigList.Source.
type AppConfigListSource string

// N400 defines model for 400.
type N400 struct {
	Code   int          `json:"code"`
	Errors *interface{} `json:"errors,omitempty"`
	Status string       `json:"status"`
}

// N403 defines model for 403.
type N403 struct {
	Code   int          `json:"code"`
	Errors *interface{} `json:"errors,omitempty"`
	Status string       `json:"status"`
}

// N404 defines model for 404.
type N404 struct {
	Code   int          `json:"code"`
	Errors *interface{} `json:"errors,omitempty"`
	Status string       `json:"status"`
}

// N409 defines model for 409.
type N409 struct {
	Code   int          `json:"code"`
	Errors *interface{} `json:"errors,omitempty"`
	Status string       `json:"status"`
}

// N500 defines model for 500.
type N500 struct {
	Code   int          `json:"code"`
	Errors *interface{} `json:"errors,omitempty"`
	Status string       `json:"status"`
}

// ListAppConfigParams defines parameters for ListAppConfig.
type ListAppConfigParams struct {
	// Page what page to render
	Page *int `form:"page,omitempty" json:"page,omitempty"`

	// ItemsPerPage item count to render per page
	ItemsPerPage        *int    `form:"itemsPerPage,omitempty" json:"itemsPerPage,omitempty"`
	AppName             string  `form:"app_name" json:"app_name"`
	Environment         string  `form:"environment" json:"environment"`
	Stack               *string `form:"stack,omitempty" json:"stack,omitempty"`
	AwsProfile          string  `form:"aws_profile" json:"aws_profile"`
	AwsRegion           string  `form:"aws_region" json:"aws_region"`
	K8sNamespace        string  `form:"k8s_namespace" json:"k8s_namespace"`
	K8sClusterId        string  `form:"k8s_cluster_id" json:"k8s_cluster_id"`
	XAwsAccessKeyId     string  `json:"X-Aws-Access-Key-Id"`
	XAwsSecretAccessKey string  `json:"X-Aws-Secret-Access-Key"`
	XAwsSessionToken    string  `json:"X-Aws-Session-Token"`
}

// SetAppConfigParams defines parameters for SetAppConfig.
type SetAppConfigParams struct {
	// Page what page to render
	Page *int `form:"page,omitempty" json:"page,omitempty"`

	// ItemsPerPage item count to render per page
	ItemsPerPage        *int    `form:"itemsPerPage,omitempty" json:"itemsPerPage,omitempty"`
	AppName             string  `form:"app_name" json:"app_name"`
	Environment         string  `form:"environment" json:"environment"`
	Stack               *string `form:"stack,omitempty" json:"stack,omitempty"`
	AwsProfile          string  `form:"aws_profile" json:"aws_profile"`
	AwsRegion           string  `form:"aws_region" json:"aws_region"`
	K8sNamespace        string  `form:"k8s_namespace" json:"k8s_namespace"`
	K8sClusterId        string  `form:"k8s_cluster_id" json:"k8s_cluster_id"`
	Key                 string  `form:"key" json:"key"`
	Value               string  `form:"value" json:"value"`
	XAwsAccessKeyId     string  `json:"X-Aws-Access-Key-Id"`
	XAwsSecretAccessKey string  `json:"X-Aws-Secret-Access-Key"`
	XAwsSessionToken    string  `json:"X-Aws-Session-Token"`
}

// DeleteAppConfigParams defines parameters for DeleteAppConfig.
type DeleteAppConfigParams struct {
	AppName             string  `form:"app_name" json:"app_name"`
	Environment         string  `form:"environment" json:"environment"`
	Stack               *string `form:"stack,omitempty" json:"stack,omitempty"`
	AwsProfile          string  `form:"aws_profile" json:"aws_profile"`
	AwsRegion           string  `form:"aws_region" json:"aws_region"`
	K8sNamespace        string  `form:"k8s_namespace" json:"k8s_namespace"`
	K8sClusterId        string  `form:"k8s_cluster_id" json:"k8s_cluster_id"`
	XAwsAccessKeyId     string  `json:"X-Aws-Access-Key-Id"`
	XAwsSecretAccessKey string  `json:"X-Aws-Secret-Access-Key"`
	XAwsSessionToken    string  `json:"X-Aws-Session-Token"`
}

// ReadAppConfigParams defines parameters for ReadAppConfig.
type ReadAppConfigParams struct {
	AppName             string  `form:"app_name" json:"app_name"`
	Environment         string  `form:"environment" json:"environment"`
	Stack               *string `form:"stack,omitempty" json:"stack,omitempty"`
	AwsProfile          string  `form:"aws_profile" json:"aws_profile"`
	AwsRegion           string  `form:"aws_region" json:"aws_region"`
	K8sNamespace        string  `form:"k8s_namespace" json:"k8s_namespace"`
	K8sClusterId        string  `form:"k8s_cluster_id" json:"k8s_cluster_id"`
	XAwsAccessKeyId     string  `json:"X-Aws-Access-Key-Id"`
	XAwsSecretAccessKey string  `json:"X-Aws-Secret-Access-Key"`
	XAwsSessionToken    string  `json:"X-Aws-Session-Token"`
}
