# Auto-generated by 'happy infra'. Do not edit
# Make improvements in happy, so that everyone can benefit.
module "stack" {
  source           = "git@github.com:chanzuckerberg/happy//terraform/modules/happy-stack-eks?ref=alokshin/init-containers"
  image_tag        = var.image_tag
  stack_name       = var.stack_name
  k8s_namespace    = var.k8s_namespace
  image_tags       = jsondecode(var.image_tags)
  stack_prefix     = "/${var.stack_name}"
  app_name         = "sidecar"
  deployment_stage = "rdev"
  services = {
    frontend = {
      cpu                              = "200m"
      cpu_requests                     = "100m"
      desired_count                    = 1
      health_check_path                = "/"
      initial_delay_seconds            = 30
      max_count                        = 1
      memory                           = "256Mi"
      memory_requests                  = "128Mi"
      name                             = "frontend"
      path                             = "/*"
      period_seconds                   = 3
      platform_architecture            = "amd64"
      port                             = 3000
      priority                         = 0
      scaling_cpu_threshold_percentage = 80
      service_type                     = "INTERNAL"
      success_codes                    = "200-399"
      synthetics                       = false

      sidecars = {
        echo = {
          image  = "ealen/echo-server"
          tag    = "0.7.0"
          port   = 80
          cpu    = "100m"
          memory = "128Mi"
        }
      }
      init_containers = {
        init = {
          image  = "ealen/echo-server"
          tag    = "0.7.0"
          cmd = [
            "sh",
            "-c",
            "echo 'hello world' > /tmp/hello-world.txt"
          ]
        }
      }
    }
  }
  create_dashboard = false
  routing_method   = "CONTEXT"
}
