// Code generated by entimport, DO NOT EDIT.

package schema

import (
	"entgo.io/ent"
	"entgo.io/ent/schema"
	"entgo.io/ent/schema/field"
	"entgo.io/contrib/entoas"
)

type AppStack struct {
	ent.Schema
}

func (AppStack) Fields() []ent.Field {
	return []ent.Field{
		field.Uint("id").SchemaType(map[string]string{"postgres": "bigserial"}),
		field.Time("created_at").Optional(),
		field.Time("updated_at").Optional(),
		field.Time("deleted_at").Optional(),
		field.String("app_name").Optional(),
		field.String("environment").Optional(),
		field.String("stack"),
	}
}
func (AppStack) Edges() []ent.Edge {
	return nil
}
func (AppStack) Annotations() []schema.Annotation {
	return []schema.Annotation{
		// Make this readonly for now
		entoas.DeleteOperation(entoas.OperationPolicy(entoas.PolicyExclude)),
		entoas.CreateOperation(entoas.OperationPolicy(entoas.PolicyExclude)),
		entoas.UpdateOperation(entoas.OperationPolicy(entoas.PolicyExclude)),
	}
}
