
# yaml-language-server: $schema=https://golangci-lint.run/jsonschema/golangci.jsonschema.json
linters:
  enable:
    - forbidigo

linters-settings:
  forbidigo:
    # These are forbidden in non-test files
    # If you have mock functions,etc that are meant to be used in tests please add them here
    forbid:
      - ^fmt\.Print.*$
      - ^spew\.Dump$
      - ^println$

issues:
  fix: true
  exclude-rules:
    # Exclude some linters from running on tests files.
    - path: _test\.go
      linters:
        - forbidigo

output:
  formats:
    - format: tab
  show-stats: true

run:
  timeout: 20m
