auth:
  oidc_client_id: "zzztestzzz"
  oidc_issuer_url: test://test.test.test
api:
  log_level: silent
  authenticated: false
database:
  driver: sqlite
  data_source_name: ":memory:"
  log_level: silent
