services:
  hapi:
    image: 626314663667.dkr.ecr.us-west-2.amazonaws.com/hapi
    platform: linux/arm64
    build:
      context: ".."
      dockerfile: ./Dockerfile.api
      args:
        - GITHUB_SHA=${GITHUB_SHA}
        - RELEASE_VERSION=${RELEASE_VERSION}
    restart: always
    ports:
      - 3001:3001
    profiles:
      - hapi
    depends_on:
      - db
    environment:
      - APP_ENV=docker-dev
      - HAPPY_DATABASE_HOST=db
      - HAPPY_DATABASE_NAME=
      - HAPPY_DATABASE_USER=postgres
      - HAPPY_DATABASE_PASSWORD=REPLACEME
      - HAPPY_DATABASE_PORT=5432
  db:
    image: postgres
    profiles:
      - hapi
    restart: always
    ports:
      - 5432:5432