version: "3.8"

services:
  happy-api:
    image: 626314663667.dkr.ecr.us-west-2.amazonaws.com/happy-api
    build:
      context: ".."
      dockerfile: ./Dockerfile.api
    restart: always
    ports:
      - 3001:3001
    profiles:
      - happy-api
    environment:
      - APP_ENV=docker-dev
      - POSTGRES_HOST=db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=REPLACEME
  db:
    image: postgres
    profiles:
      - happy-api
    restart: always
    ports:
      - 5432:5432
