version: "3.8"
services:
  hapi:
    image: hapi
    platform: linux/arm64
    build:
      context: ".."
      dockerfile: ./Dockerfile.api
      args:
        - GITHUB_SHA=${GITHUB_SHA}
        - RELEASE_VERSION=${RELEASE_VERSION}
    restart: always
    ports:
      - 3001:3001
    profiles:
      - hapi
    depends_on:
      db:
        condition: service_healthy
    environment:
      - APP_ENV=docker-dev
      - HAPPY_DATABASE_HOST=db
      - HAPPY_DATABASE_NAME=postgres
      - HAPPY_DATABASE_USER=postgres
      - HAPPY_DATABASE_PASSWORD=REPLACEME
      - HAPPY_DATABASE_PORT=5432
  db:
    image: postgres
    profiles:
      - hapi
    restart: always
    command: postgres -c 'max_connections=500'
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=REPLACEME
      - POSTGRES_DB=postgres
      - PGPASSWORD=REPLACEME
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
