on:
  - pull_request

name: api-build
jobs:
  lint-api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version-file: api/go.mod
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.49.0
          github-token: ${{ secrets.GITHUB_TOKEN }}
          args: --timeout 3m0s
          working-directory: api

  test-api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version-file: api/go.mod
      - name: Run tests
        run: cd api && make test
