on:
  pull_request:
    paths:
      - .github/**
      - api/**
      - shared/**

name: api-build
jobs:
  lint-api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version-file: api/go.mod
      - name: Run go mod tidy
        run: |
          go mod tidy
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          github-token: ${{ secrets.GITHUB_TOKEN }}
          args: --timeout 10m0s
          skip-go-installation: true
          working-directory: api

  test-api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version-file: api/go.mod
      - name: Run go mod tidy
        run: |
          go mod tidy
      - name: Run tests
        run: cd api && make test
