on:
  push:
    branches:
      - main
      - hspitzley/sentry_otel

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
name: api-release-staging
jobs:
  release-api:
    runs-on: [ARM64, self-hosted, Linux]
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Assume happy-api deployement role
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: us-west-2
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME_STAGING }}
          role-duration-seconds: 1200
          role-session-name: HappyApiUpdateStaging
      - uses: actions/checkout@v3
      - name: Update staging
        uses: chanzuckerberg/github-actions/.github/actions/deploy-happy-stack@deploy-happy-stack-v1.14.0
        with:
          tfe-token: ${{ secrets.TFE_TOKEN }}
          env: staging
          create-tag: true
          stack-name: hapi
          working-directory: api
          version-lock-file: api/.happy/version.lock
        env:
          RELEASE_VERSION: staging-release
