on:
  push:
    branches:
      - main
      - hspitzley/fix_credentials

name: api-release-staging
jobs:
  release-api:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Assume happy-api deployement role
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: us-west-2
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME_STAGING }}
          role-duration-seconds: 1200
          role-session-name: HappyApiUpdateStaging
      - uses: actions/checkout@v3
      - name: Update staging
        uses: chanzuckerberg/github-actions/.github/actions/deploy-happy-stack@deploy-happy-stack-v1.7.2
        with:
          tfe-token: ${{ secrets.TFE_TOKEN }}
          env: staging
          create-tag: true
          stack-name: hapi
          working-directory: api
          happy_version: 0.40.1
        env:
          RELEASE_VERSION: staging-release
