on:
  push:
    paths-ignore:
      - VERSION
      - LICENSE
      - "**.md"

name: build
jobs:
  test:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - name: Run tests
        run: make test
