name: Release Charts

on:
  release:
    types: [published]

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
  check-chart-released:
    runs-on: [ARM64, self-hosted, Linux]
    steps:
      - name: Check Release
        id: chart_released
        uses: actions/github-script@v5
        with:
          result-encoding: string
          script: |
            console.log("REF")
            console.log(context.ref)
            return context.ref.includes('refs/tags/happy-stack-helm')
    outputs:
      chart_released: ${{ steps.chart_released.outputs.result }}
  release:
    if: ${{ needs.check-chart-released.outputs.chart_released == 'true' }}
    needs:
      - check-chart-released
    # NOTE: needs to be X64 because of helm-releaser
    runs-on: [X64, self-hosted, Linux]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
      - name: Run chart-releaser
        uses: helm/chart-releaser-action@main
        with:
            charts_dir: helm-charts/charts
        env:
          CR_TOKEN: ${{ secrets.GITHUB_TOKEN }}