name: Release Charts

on:
  pull_request:
    branches:
      - helmify

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
  release:
    # NOTE: needs to be X64 because of helm-releaser
    runs-on: [X64, self-hosted, Linux]
    steps:
      - name: Generate token
        id: generate_token
        uses: chanzuckerberg/github-app-token@v1.1.4
        with:
            app_id: ${{ secrets.CZI_GITHUB_HELPER_APP_ID }}
            private_key: ${{ secrets.CZI_GITHUB_HELPER_PK }}
      - name: Checkout
        uses: actions/checkout@v3
        with:
            token: ${{ steps.generate_token.outputs.token }}
      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
      - name: Run chart-releaser
        uses: helm/chart-releaser-action@main
        with:
            charts_dir: helm-charts/charts
            pages_branch: ${{ github.base_ref }}
        env:
          CR_TOKEN: ${{ steps.generate_token.outputs.token }}