on:
  - pull_request

name: build
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.44.0
          github-token: ${{ secrets.GITHUB_TOKEN }}
          skip-go-installation: true
          args: --timeout 3m0s

      - name: Run tests
        run: make coverage
