on:
  - pull_request

name: build
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: lint-staticcheck
        uses: dominikh/staticcheck-action@v1.1.0
        with:
          version: "2021.1.1"
          install-go: false
          cache-key: "1.17"
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: latest
          github-token: ${{ secrets.GITHUB_TOKEN }}
          only-new-issues: true
          skip-go-installation: true

      - name: Run tests
        run: make coverage
