name: Release the CLI
on:
  release:
    types: [published]

name: release-cli
jobs:
  go-release:
    runs-on: ubuntu-latest
    steps:
      - name: Check Release
        id: cli_released
        uses: actions/github-script@v5
        with:
          result-encoding: string
          script: |
            const tag = context.ref.replace('refs/tags/', '')
            return tag.includes('happy-v')

      # See https://docs.github.com/en/actions/security-guides/automatic-token-authentication#using-the-github_token-in-a-workflow
      # For why we need to generate a token and not use the default
      - name: Generate token
        id: generate_token
        uses: chanzuckerberg/github-app-token@v1.1.4
        if: ${{ steps.cli_released.outputs.result === 'true' }}
        with:
          app_id: ${{ secrets.CZI_RELEASE_PLEASE_APP_ID }}
          private_key: ${{ secrets.CZI_RELEASE_PLEASE_PK }}
      - uses: actions/checkout@v2
        if: ${{ steps.cli_released.outputs.result === 'true' }}
        # we need to fetch all history and tags,
        # so we build the proper version
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v3
        if: ${{ steps.cli_released.outputs.result === 'true' }}
        with:
          go-version-file: cli/go.mod
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        if: ${{ steps.cli_released.outputs.result === 'true' }}
        with:
          version: latest
          workdir: cli
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}
