on:
  release:
    types: [published]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
name: release-cli
jobs:
  check-cli-released:
    runs-on: ARM64
    steps:
      - name: Check Release
        id: cli_released
        uses: actions/github-script@v5
        with:
          result-encoding: string
          script: return context.ref.includes('refs/tags/cli-v')
    outputs:
      cli_released: ${{ steps.cli_released.outputs.result }}

  go-release-cli:
    runs-on: ARM64
    if: ${{ needs.check-cli-released.outputs.cli_released == 'true' }}
    needs:
      - check-cli-released
    steps:
      # See https://docs.github.com/en/actions/security-guides/automatic-token-authentication#using-the-github_token-in-a-workflow
      # For why we need to generate a token and not use the default
      - name: Generate token
        id: generate_token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.CZI_RELEASE_PLEASE_APP_ID }}
          private-key: ${{ secrets.CZI_RELEASE_PLEASE_PK }}
      - name: Parse Version
        id: parse_version
        uses: actions/github-script@v5
        with:
          result-encoding: string
          script: return context.ref.replace('refs/tags/cli-', '')
      - name: Create overall repo tag
        uses: actions/github-script@v5
        with:
          script: |
            try {
              await github.rest.git.createRef({
                owner: context.repo.owner,
                repo: context.repo.repo,
                ref: 'refs/tags/${{ steps.parse_version.outputs.result }}',
                sha: context.sha
              })
            } catch(e) {
              // tag may have existed, ignore the error
              console.log(e)
            }
      - uses: actions/checkout@v3
        # we need to fetch all history and tags,
        # so we build the proper version
        # NOTE: this needs to happen after the tag is created so the tag is present locally
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v4
        with:
          go-version-file: cli/go.mod
          cache: true
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v3
        with:
          version: v1.26.2
          workdir: cli
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}
          GORELEASER_CURRENT_TAG: ${{ steps.parse_version.outputs.result }}

  create_and_release_jira_version:
    # only run for cli releases
    if: ${{ needs.check-cli-released.outputs.cli_released == 'true' }}
    needs:
      - check-cli-released
      - go-release-cli # we need to wait for the release to finish before creating the jira version
    uses: chanzuckerberg/github-actions/.github/workflows/jira-release-version.yaml@v2.13.1
    with:
      projectID: '12399'
      projectKey: CCIE
      jiraVersionPrefix: 'Happy'
    secrets:
      jiraToken: ${{ secrets.JIRA_TOKEN }}
