on:
  - pull_request

name: cli-build
jobs:
  lint-cli:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version-file: cli/go.mod
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.49.0
          github-token: ${{ secrets.GITHUB_TOKEN }}
          args: --timeout 10m0s
          working-directory: cli

  test-cli:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version-file: cli/go.mod
  
      - name: Update coverage
        run: cd cli && make coverage-update

      - name: Generate token
        id: generate_token
        uses: chanzuckerberg/github-app-token@v1.1.4
        with:
          app_id: ${{ secrets.CZI_RELEASE_PLEASE_APP_ID }}
          private_key: ${{ secrets.CZI_RELEASE_PLEASE_PK }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ steps.generate_token.outputs.token }}
          branch: bot/update-coverage
          commit-message: "chore: Update coverage"
          title: "chore: Update coverage"

      - name: Run tests
        run: cd cli && make coverage
