on:
  - pull_request

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
name: hvm-build
jobs:
  hvm_changes:
    runs-on: ARM64
    permissions:
      pull-requests: read
    outputs:
      run_hvm_ci: ${{ steps.filter.outputs.dependencies }}
    steps:
    - name: Check for changed files
      uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          dependencies:
            - '.github/**'
            - 'hvm/**'
            - 'shared/**'
  lint-cli:
    needs: hvm_changes
    if: ${{ needs.cli_changes.outputs.run_hvm_ci == 'true' }}
    runs-on: ARM64
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version-file: hvm/go.mod
          cache: true
      - name: Run go mod tidy
        working-directory: hvm
        run: go mod tidy
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.63.4
          github-token: ${{ secrets.GITHUB_TOKEN }}
          args: --timeout 20m0s -v
          working-directory: hvm
          skip-pkg-cache: true

  test-cli:
    needs: hvm_changes
    if: ${{ needs.hvm_changes.outputs.run_hvm_ci == 'true' }}
    runs-on: ARM64
    steps:
      - name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@v2
        with:
          app_id: ${{ secrets.CZI_RELEASE_PLEASE_APP_ID }}
          private_key: ${{ secrets.CZI_RELEASE_PLEASE_PK }}

      - uses: actions/checkout@v3
        with:
          token: ${{ steps.generate_token.outputs.token }}
          ref: ${{ github.event.pull_request.head.ref }}

      - uses: actions/setup-go@v4
        with:
          go-version-file: hvm/go.mod
          cache: true
      - name: Run go mod tidy
        run: |
          cd hvm && go mod tidy

      - name: Update coverage
        if: github.actor!= 'dependabot[bot]'
        run: cd hvm && make coverage-update

      - name: Commit updated coverage
        uses: EndBug/add-and-commit@v9
        with:
          add: -A
          message: commit from hvm-ci -- updated coverage

      - name: Run tests
        run: cd hvm && make coverage
