on:
    push:
      branches:
        - main
        - alokshin/integration-test
name: integration-test
jobs:
    integration-test:
      runs-on: ubuntu-latest
      steps:
        - name: Assume happy-api deployement role
          uses: aws-actions/configure-aws-credentials@v1
          with:
            aws-region: us-west-2
            role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME_DEV }}
            role-duration-seconds: 1200
            role-session-name: HappyCLIIntegrationTest
        - uses: actions/checkout@v3
        - uses: actions/setup-go@v3
          with:
            go-version-file: cli/go.mod
        - name: Build CLI
          run: go build -o happy
          working-directory: ./cli
        - name: List stacks
          run: ../../cli/happy --aws-profile="" list
          working-directory: ./examples/typical_app

  