on:
    push:
      branches:
        - main
        - alokshin/integration-test
name: integration-test
jobs:
    integration-test:
      runs-on: ubuntu-latest
      permissions:
        id-token: write
        contents: read
      env:
        TFE_TOKEN: ${{ secrets.TFE_TOKEN_INTEGRATION_PLAYGROUND }}
      steps:
        - name: Assume happy-api deployement role
          uses: aws-actions/configure-aws-credentials@v2
          with:
            aws-region: us-west-2
            role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME_INTEGRATION_PLAYGROUND }}
            role-duration-seconds: 1200
            role-session-name: HappyCLIIntegrationTest
        # - id: install-aws-cli
        #   uses: unfor19/install-aws-cli-action@v1
        #   with:
        #     version: 2     
        #     verbose: false
        #     arch: amd64
        # - name: Identity info
        #   run: |
        #       aws sts get-caller-identity
        # - name: Update kube config
        #   run: | 
        #     aws eks update-kubeconfig --name si-playground-eks-v2 --alias si-playground-eks-v2 --region us-west-2
        #     kubectl config use-context si-playground-eks-v2
        # - uses: azure/setup-kubectl@v3
        # - name: Retrieve a list of nodes
        #   run: |
        #     kubectl get svc
        - uses: actions/checkout@v3
        - uses: actions/setup-go@v3
          with:
            go-version-file: cli/go.mod
        - name: Cache Go modules
          uses: actions/cache@v3
          with:
            path: |
              ~/go/pkg/mod
            key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
            restore-keys: |
              ${{ runner.os }}-go-
        - name: Build CLI
          run: go build -o happy
          working-directory: ./cli
        - name: List stacks
          run: ../../cli/happy --detached --aws-profile="" list --output json
          working-directory: ./examples/integration_test
        - name: Create a stack
          run: ../../cli/happy --detached --aws-profile="" create integration-test --force -v
          working-directory: ./examples/integration_test
        - name: Update a stack
          run: ../../cli/happy --detached --aws-profile="" update integration-test -v
          working-directory: ./examples/integration_test
        - name: Delete a stack
          run: ../../cli/happy --detached --aws-profile="" delete integration-test --force -v
          working-directory: ./examples/integration_test

  