on:
  release:
    types: [published]

name: Jira Release

jobs:
  check_release:
    runs-on: [ARM64, self-hosted, Linux]
    steps:
      - name: Check Release
        id: is_root_release
        uses: actions/github-script@v5
        with:
          result-encoding: string
          script: return context.ref.includes('refs/tags/v')
    outputs:
      is_root_release: ${{ steps.is_root_release.outputs.result }}

  create_and_release_jira_version:
    # prevent running on releases that are not root releases
    # ie, api and cli releases, tagged like "api-v1.2.3", should not trigger this job
    if: ${{ needs.check_release.outputs.is_root_release == 'true' }}
    needs:
      - check_release
    uses: chanzuckerberg/github-actions/.github/workflows/jira-release-version.yaml@v1.18.1
    with:
      projectID: '10006'
      projectKey: CCIE
      jiraVersionPrefix: 'Happy'
    secrets:
      jiraToken: ${{ secrets.JIRA_TOKEN }}
