on:
  release:
    types: [published]

name: Jira Release

jobs:
  check_release:
    runs-on: [ARM64, self-hosted, Linux]
    steps:
      - name: Check Release
        id: checkRelease
        uses: actions/github-script@v6
        with:
          script: |
            if (context.ref.includes('refs/tags/api-v') || context.ref.includes('refs/tags/cli-v')) {
              core.setOutput('create_jira_release', 'true');
            } else {
              core.setOutput('create_jira_release', 'false');
            }
    outputs:
      create_jira_release: ${{ steps.checkRelease.outputs.create_jira_release }}

  create_and_release_jira_version:
    # only run for api and cli releases
    if: ${{ needs.check_release.outputs.create_jira_release == 'true' }}
    needs: check_release
    uses: chanzuckerberg/github-actions/.github/workflows/jira-release-version.yaml@v1.20.4
    with:
      projectID: '10006'
      projectKey: CCIE
      jiraVersionPrefix: 'Happy'
    secrets:
      jiraToken: ${{ secrets.JIRA_TOKEN }}
