on:
  - pull_request

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

name: provider-build
jobs:
  provider_changes:
    runs-on: [ARM64, self-hosted, Linux]
    permissions:
      pull-requests: read
    outputs:
      run_provider_ci: ${{ steps.filter.outputs.dependencies }}
    steps:
    - name: Check for changed files
      uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          dependencies:
            - '.github/**'
            - 'shared/**'
            - 'terraform/provider/**'
  lint-provider:
    needs: provider_changes
    if: ${{ needs.provider_changes.outputs.run_provider_ci == 'true' }}
    runs-on: [ARM64, self-hosted, Linux]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version-file: terraform/provider/go.mod
          cache: true
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.63.4
          github-token: ${{ secrets.GITHUB_TOKEN }}
          args: --timeout 20m0s -v
          working-directory: terraform/provider
          skip-pkg-cache: true

  test-provider:
    needs: provider_changes
    if: ${{ needs.provider_changes.outputs.run_provider_ci == 'true' }}
    runs-on: [ARM64, self-hosted, Linux]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version-file: terraform/provider/go.mod
          cache: true
      - name: Run tests
        run: cd terraform/provider && make test
