on:
  pull_request:
    paths:
      - 'terraform/provider/**.go'

name: provider-build
jobs:
  lint-provider:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version-file: terraform/provider/go.mod
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          github-token: ${{ secrets.GITHUB_TOKEN }}
          args: --timeout 10m0s
          skip-go-installation: true
          working-directory: terraform/provider

  test-provider:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version-file: terraform/provider/go.mod
      - name: Run tests
        run: cd terraform/provider && make test
