on:
  - pull_request

name: provider-build
jobs:
  lint-provider:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version-file: terraform/provider/go.mod
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.49.0
          github-token: ${{ secrets.GITHUB_TOKEN }}
          args: --timeout 3m0s
          working-directory: terraform/provider

  test-provider:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version-file: terraform/provider/go.mod
      - name: Run tests
        run: cd terraform/provider && make test
