on:
  push:
    branches:
      - main

name: release-please
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v5
        id: configure-changelog
        with:
          result-encoding: string
          script: |
            const changelogTypes = [
              {type: "feat", section: "Features", hidden: false},
              {type: "chore", section: "Misc", hidden: false},
              {type: "fix", section: "BugFixes", hidden: false},
            ]

            return JSON.stringify(changelogTypes)
      # See https://docs.github.com/en/actions/security-guides/automatic-token-authentication#using-the-github_token-in-a-workflow
      # For why we need to generate a token and not use the default
      - name: Generate token
        id: generate_token
        uses: chanzuckerberg/github-app-token@v1.1.4
        with:
          app_id: ${{ secrets.CZI_RELEASE_PLEASE_APP_ID }}
          private_key: ${{ secrets.CZI_RELEASE_PLEASE_PK }}

      - name: release please
        uses: google-github-actions/release-please-action@v3
        id: release
        with:
          release-type: simple
          bump-minor-pre-major: true
          changelog-types: ${{ steps.configure-changelog.outputs.result }}
          token: ${{ steps.generate_token.outputs.token }}

      - uses: actions/checkout@v2
        # we need to fetch all history and tags,
        # so we build the proper version
        with:
          fetch-depth: 0

      - uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Generate Prerelease Version
        id: generate_tag
        run: |
          VERSION=v$(cat version.txt)-$(git rev-parse --short HEAD)
          echo "::set-output name=tag-name::$VERSION"
        if: ${{ github.event_name == 'release' && github.event.release.prerelease }}

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}
        if: ${{ steps.release.outputs.release_created }}

      - name: Tag snapshot
        uses: tvdias/github-tagger@v0.0.1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ steps.generate_tag.outputs.tag-name }}
        if: ${{ github.event_name == 'release' && github.event.release.prerelease }}

      - name: Prerelease
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --rm-dist -f .goreleaser.prerelease.yml
        env:
          GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}
          GORELEASER_CURRENT_TAG: ${{ steps.generate_tag.outputs.tag-name }}
        if: ${{ github.event_name == 'release' && github.event.release.prerelease }}
