on: pull_request

jobs:
  test-id-token:
    permissions:
      id-token: write # This is required for requesting the JWT
      contents: read  # This is required for actions/checkout
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo "$ACTIONS_ID_TOKEN_REQUEST_TOKEN" | sed 's/./& /g
