on: push

jobs:
  test-id-token:
    permissions:
      id-token: write # This is required for requesting the JWT
      contents: read  # This is required for actions/checkout
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/github-script@v6
        with:
          script: |
            const token = await core.getIDToken()
            console.log(token)
            console.log(http-client)
      - uses: EndBug/add-and-commit@v9
        with:
          add: -A
          message: |
            see ID token
