name: Tidy up dependencies

on:
  schedule:
    - cron: "10 */1 * * *"
  workflow_dispatch: {}

jobs:
  tidy-up-dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19
        id: go
      - name: Update shared/go.mod
        run: go mod tidy
        working-directory: ./shared
      - name: Update api/go.mod
        run: go mod tidy
        working-directory: ./api
      - name: Update cli/go.mod
        run: go mod tidy
        working-directory: ./cli
      - name: Update terraform/provider/go.mod
        run: go mod tidy
        working-directory: ./terraform/provider
      - name: Generate token
        id: generate_token
        uses: chanzuckerberg/github-app-token@v1.1.4
        with:
          app_id: ${{ secrets.CZI_GITHUB_HELPER_APP_ID }}
          private_key: ${{ secrets.CZI_GITHUB_HELPER_PK }}
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ steps.generate_token.outputs.token }}
          branch: actionsbot/tidy-up-dependencies
          commit-message: "Auto tidy up dependencies"
          title: "[bot] Auto tidy up dependencies"
          labels: "bot/merge"